[package]
name = "luna"
version = "0.4.0"
authors = ["SAoirse: github.com/XAoirse"]
description = "A Recon Tool"
readme = "README.md"
edition = "2021"

# RUSTFLAGS='-C target-feature=+crt-static -C link-arg=-s' cargo build --target x86_64-unknown-linux-musl --release


# Should be in .cargo/config
# # https://blog.davidvassallo.me/2021/06/10/lessons-learned-building-statically-linked-rust-binaries-openssl/
# [target.x86_64-unknown-linux-musl]
# # https://doc.rust-lang.org/reference/linkage.html#static-and-dynamic-c-runtimes
# # rustflags = ["-C", "target-feature=+crt-static"]
#
# # -s, --strip-all Omit all symbol information from the output file.
# rustflags = ["-C", "link-arg=-s"]
# target = "x86_64-unknown-linux-musl"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# https://docs.rs/openssl/0.10.36/openssl/#vendored
openssl = { version = "*", features = ["vendored"] }
log = "0.4"
env_logger = "0.8.4"
colored = "2"
chrono = "0.4"
clap = { version = "2.33.3", features = ["yaml","suggestions", "color","wrap_help" ] }
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
serde_json = "1.0.68"
rayon = "1.5"
