[package]
name = "luna"
version = "0.6.0"
authors = ["SAoirse: github.com/XAoirse"]
description = "A Recon Tool"
readme = "README.md"
edition = "2021"


[dependencies]
# https://docs.rs/openssl/0.10.36/openssl/#vendored
openssl = { version = "*", features = ["vendored"] }
log = "0.4"
env_logger = "0.8.4"
colored = "2"
chrono = "0.4"
clap = { version = "2.33.3", features = ["suggestions", "color","wrap_help" ] }
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
serde_json = "1.0.68"
rayon = "1.5"
cidr = "0.2.1"
signal-hook = "*"
indicatif = {version = "0.17.0-rc.5", features = ["rayon"]}
url = "2.2.2"